FROM java:8
LABEL maintainer "abuzain1995@gmail.com"
EXPOSE 8080
ADD /target/ISW-Onboarding-0.0.1-SNAPSHOT.jar ISW-Onboarding-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","ISW-Onboarding-0.0.1-SNAPSHOT.jar"]